version: 0.0
os: linux
files:
  - source: /
    destination: /Django-Chat-Application
hooks:
  BeforeInstall:
     - location: scripts/stop_server.sh
       timeout: 300
       runas: root
  AfterInstall:
    - location: scripts/supervisorStart.sh
      timeout: 300
      runas: root
